intercept-console-error.ts:41 Error fetching user data: FirebaseError: Failed to get document because the client is offline. error	@	intercept-console-error.ts:41